#Client only settings, mostly things related to rendering
[client]
	#EXPERIMENTAL: Enable the Forge block rendering pipeline - fixes the lighting of custom models.
	experimentalForgeLightPipelineEnabled = false
	#When enabled, Forge will show any warnings that occurred during loading.
	showLoadWarnings = true
